image: node:24

before_script:
  - corepack enable
  - pnpm config set store-dir .pnpm-store

stages:
  - build
  - test

cache:
  paths:
    - .pnpm-store/

install_dependencies:
  stage: build
  script:
    - pnpm install --frozen-lockfile
    - mkdir -p output/static
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  script:
    - pnpm test
    - mkdir -p output/static
