image: node:24

before_script:
  - corepack enable
  - pnpm config set store-dir .pnpm-store

stages:
  - build
  - test

cache:
  paths:
    - .pnpm-store/

install_dependencies:
  stage: build
  script:
    - pnpm install --frozen-lockfile
    - mkdir -p output/static
  artifacts:
    paths:
      - node_modules/

testing_fast_jest:
  stage: test
  script:
    - pnpm run build-no-lint
    - pnpm run test:fast:jest
    - mkdir -p output/static

testing_fast_node:
  stage: test
  script:
    - pnpm run build-no-lint
    - pnpm run test:fast:node
    - mkdir -p output/static

testing_slow_jest:
  stage: test
  script:
    - pnpm run build-no-lint
    - pnpm run test:slow:jest
    - mkdir -p output/static

testing_slow_node:
  stage: test
  script:
    - pnpm run build-no-lint
    - pnpm run test:slow:node
    - mkdir -p output/static
